### ISSUE TITLE
Inf-ruby: certificate verify failed

### ISSUE THREAD

**Issue by JamesYuan** [bbatsov/prelude#804]
I try to execute a HTTPS in inf-ruby mode, it failed as followings. But it works well in Bash command line.

irb(main):001:0> load ('./get-email-request.rb')
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
	from /usr/lib/ruby/1.9.1/net/http.rb:800:in `connect'
	from /usr/lib/ruby/1.9.1/net/http.rb:800:in `block in connect'
	from /usr/lib/ruby/1.9.1/timeout.rb:55:in `timeout'
	from /usr/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
	from /usr/lib/ruby/1.9.1/net/http.rb:800:in `connect'
	from /usr/lib/ruby/1.9.1/net/http.rb:756:in `do_start'
	from /usr/lib/ruby/1.9.1/net/http.rb:745:in `start'
	from /usr/lib/ruby/1.9.1/net/http.rb:1285:in `request'
	from /home/jyuan/projects/opensources/eloqua-ruby-request/eloqua-ruby-request.rb:52:in `request'
	from /home/jyuan/projects/opensources/eloqua-ruby-request/eloqua-ruby-request.rb:31:in `get'
	from /home/jyuan/projects/opensources/eloqua-ruby-request/examples/get-email-request.rb:10:in `<top (required)>'
	from (irb):9:in `load'
	from (irb):9
	from /usr/bin/irb:12:in `<main>'
irb(main):010:0> 

Thanks,
James.

**Comment by JamesYuan** [comment]
It seems different ruby between emacs and bash
-rwxrwxr-x 1 jyuan jyuan 12285  2月  8 12:03 /home/jyuan/.rvm/rubies/ruby-1.9.3-p551/bin/ruby*

**Comment by JamesYuan** [comment]
It works well after adding https://github.com/senny/rvm.el.

Thanks.
